# Phase 8 — Classification

## Predicting Good Investment Properties

### Objective
Build and evaluate multiple machine learning classification models to predict whether a property is a `Good_Investment`.

### Target Variable
`Good_Investment`

### Models
1. Logistic Regression
2. Decision Tree
3. Random Forest
4. Extra Trees
5. XGBoost

### Evaluation Metrics
- Accuracy
- Precision
- Recall
- F1 Score
- ROC AUC
- Confusion Matrix

In [ ]:
import pandas as pd
import numpy as np
import joblib
import os

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, ExtraTreesClassifier
from xgboost import XGBClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

print("Libraries imported successfully.")

Libraries imported successfully.


In [ ]:
X_train_cls = joblib.load("../models/X_train_cls_processed.pkl")
X_test_cls = joblib.load("../models/X_test_cls_processed.pkl")

y_train_cls = joblib.load("../models/y_train_cls.pkl")
y_test_cls = joblib.load("../models/y_test_cls.pkl")

print("Classification data loaded successfully.")
print("Training features:", X_train_cls.shape)
print("Testing features :", X_test_cls.shape)
print("Training target   :", y_train_cls.shape)
print("Testing target    :", y_test_cls.shape)

Classification data loaded successfully.
Training features: (200000, 604)
Testing features : (50000, 604)
Training target   : (200000,)
Testing target    : (50000,)


In [ ]:
# Logistic Regression

logistic_model = LogisticRegression(
    max_iter=1000,
    solver="saga",
    random_state=42
)

logistic_model.fit(
    X_train_cls,
    y_train_cls
)

print("Logistic Regression trained successfully.")

Logistic Regression trained successfully.


In [ ]:
# Logistic Regression Predictions

y_pred_logistic = logistic_model.predict(X_test_cls)
y_prob_logistic = logistic_model.predict_proba(X_test_cls)[:, 1]

print("Predictions generated successfully.")

Predictions generated successfully.


In [ ]:
# Evaluate Logistic Regression

accuracy = accuracy_score(y_test_cls, y_pred_logistic)
precision = precision_score(y_test_cls, y_pred_logistic)
recall = recall_score(y_test_cls, y_pred_logistic)
f1 = f1_score(y_test_cls, y_pred_logistic)
roc_auc = roc_auc_score(y_test_cls, y_prob_logistic)

print("Logistic Regression Results")
print("=" * 40)
print(f"Accuracy : {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall   : {recall:.4f}")
print(f"F1 Score : {f1:.4f}")
print(f"ROC AUC  : {roc_auc:.4f}")

Logistic Regression Results
Accuracy : 0.9346
Precision: 0.9370
Recall   : 0.9376
F1 Score : 0.9373
ROC AUC  : 0.9874


In [ ]:
# Confusion Matrix

cm_logistic = confusion_matrix(
    y_test_cls,
    y_pred_logistic
)

print("Confusion Matrix:")
print(cm_logistic)

Confusion Matrix:
[[22293  1644]
 [ 1626 24437]]


In [ ]:
# Decision Tree Classifier

decision_tree_model = DecisionTreeClassifier(
    random_state=42,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=5
)

decision_tree_model.fit(
    X_train_cls,
    y_train_cls
)

print("Decision Tree trained successfully.")

Decision Tree trained successfully.


In [ ]:
# Decision Tree Predictions

y_pred_dt = decision_tree_model.predict(X_test_cls)
y_prob_dt = decision_tree_model.predict_proba(X_test_cls)[:, 1]

print("Decision Tree predictions generated successfully.")

Decision Tree predictions generated successfully.


In [ ]:
# Evaluate Decision Tree

accuracy_dt = accuracy_score(y_test_cls, y_pred_dt)
precision_dt = precision_score(y_test_cls, y_pred_dt)
recall_dt = recall_score(y_test_cls, y_pred_dt)
f1_dt = f1_score(y_test_cls, y_pred_dt)
roc_auc_dt = roc_auc_score(y_test_cls, y_prob_dt)

print("Decision Tree Results")
print("=" * 40)
print(f"Accuracy : {accuracy_dt:.4f}")
print(f"Precision: {precision_dt:.4f}")
print(f"Recall   : {recall_dt:.4f}")
print(f"F1 Score : {f1_dt:.4f}")
print(f"ROC AUC  : {roc_auc_dt:.4f}")

Decision Tree Results
Accuracy : 1.0000
Precision: 1.0000
Recall   : 1.0000
F1 Score : 1.0000
ROC AUC  : 1.0000


In [ ]:
cm_dt = confusion_matrix(
    y_test_cls,
    y_pred_dt
)

print("Decision Tree Confusion Matrix:")
print(cm_dt)

Decision Tree Confusion Matrix:
[[23936     1]
 [    0 26063]]


In [ ]:
# Random Forest Classifier

random_forest_model = RandomForestClassifier(
    n_estimators=100,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)

random_forest_model.fit(
    X_train_cls,
    y_train_cls
)

print("Random Forest trained successfully.")

Random Forest trained successfully.


In [ ]:
# Random Forest Predictions

y_pred_rf = random_forest_model.predict(X_test_cls)
y_prob_rf = random_forest_model.predict_proba(X_test_cls)[:, 1]

print("Random Forest predictions generated successfully.")

Random Forest predictions generated successfully.


In [ ]:
# Evaluate Random Forest

accuracy_rf = accuracy_score(y_test_cls, y_pred_rf)
precision_rf = precision_score(y_test_cls, y_pred_rf)
recall_rf = recall_score(y_test_cls, y_pred_rf)
f1_rf = f1_score(y_test_cls, y_pred_rf)
roc_auc_rf = roc_auc_score(y_test_cls, y_prob_rf)

print("Random Forest Results")
print("=" * 40)
print(f"Accuracy : {accuracy_rf:.4f}")
print(f"Precision: {precision_rf:.4f}")
print(f"Recall   : {recall_rf:.4f}")
print(f"F1 Score : {f1_rf:.4f}")
print(f"ROC AUC  : {roc_auc_rf:.4f}")

Random Forest Results
Accuracy : 0.9987
Precision: 0.9976
Recall   : 0.9999
F1 Score : 0.9987
ROC AUC  : 1.0000


In [ ]:
cm_rf = confusion_matrix(
    y_test_cls,
    y_pred_rf
)

print("Random Forest Confusion Matrix:")
print(cm_rf)

Random Forest Confusion Matrix:
[[23873    64]
 [    2 26061]]


In [ ]:
# Extra Trees Classifier

extra_trees_model = ExtraTreesClassifier(
    n_estimators=100,
    max_depth=15,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42,
    n_jobs=-1
)

extra_trees_model.fit(
    X_train_cls,
    y_train_cls
)

print("Extra Trees trained successfully.")

Extra Trees trained successfully.


In [ ]:
# Extra Trees Predictions

y_pred_et = extra_trees_model.predict(X_test_cls)
y_prob_et = extra_trees_model.predict_proba(X_test_cls)[:, 1]

print("Extra Trees predictions generated successfully.")

Extra Trees predictions generated successfully.


In [ ]:
# Evaluate Extra Trees

accuracy_et = accuracy_score(y_test_cls, y_pred_et)
precision_et = precision_score(y_test_cls, y_pred_et)
recall_et = recall_score(y_test_cls, y_pred_et)
f1_et = f1_score(y_test_cls, y_pred_et)
roc_auc_et = roc_auc_score(y_test_cls, y_prob_et)

print("Extra Trees Results")
print("=" * 40)
print(f"Accuracy : {accuracy_et:.4f}")
print(f"Precision: {precision_et:.4f}")
print(f"Recall   : {recall_et:.4f}")
print(f"F1 Score : {f1_et:.4f}")
print(f"ROC AUC  : {roc_auc_et:.4f}")

Extra Trees Results
Accuracy : 0.9247
Precision: 0.9286
Recall   : 0.9268
F1 Score : 0.9277
ROC AUC  : 0.9802


In [ ]:
cm_et = confusion_matrix(
    y_test_cls,
    y_pred_et
)

print("Extra Trees Confusion Matrix:")
print(cm_et)

Extra Trees Confusion Matrix:
[[22079  1858]
 [ 1909 24154]]


In [ ]:
# XGBoost Classifier

xgb_model = XGBClassifier(
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    n_jobs=-1
)

xgb_model.fit(
    X_train_cls,
    y_train_cls
)

print("XGBoost trained successfully.")

XGBoost trained successfully.


In [ ]:
# XGBoost Predictions

y_pred_xgb = xgb_model.predict(X_test_cls)
y_prob_xgb = xgb_model.predict_proba(X_test_cls)[:, 1]

print("XGBoost predictions generated successfully.")

XGBoost predictions generated successfully.


In [ ]:
# Evaluate XGBoost

accuracy_xgb = accuracy_score(y_test_cls, y_pred_xgb)
precision_xgb = precision_score(y_test_cls, y_pred_xgb)
recall_xgb = recall_score(y_test_cls, y_pred_xgb)
f1_xgb = f1_score(y_test_cls, y_pred_xgb)
roc_auc_xgb = roc_auc_score(y_test_cls, y_prob_xgb)

print("XGBoost Results")
print("=" * 40)
print(f"Accuracy : {accuracy_xgb:.4f}")
print(f"Precision: {precision_xgb:.4f}")
print(f"Recall   : {recall_xgb:.4f}")
print(f"F1 Score : {f1_xgb:.4f}")
print(f"ROC AUC  : {roc_auc_xgb:.4f}")

XGBoost Results
Accuracy : 0.9998
Precision: 1.0000
Recall   : 0.9996
F1 Score : 0.9998
ROC AUC  : 1.0000


In [ ]:
cm_xgb = confusion_matrix(
    y_test_cls,
    y_pred_xgb
)

print("XGBoost Confusion Matrix:")
print(cm_xgb)

XGBoost Confusion Matrix:
[[23937     0]
 [   11 26052]]


In [ ]:
# Classification Model Comparison

classification_results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Decision Tree",
        "Random Forest",
        "Extra Trees",
        "XGBoost"
    ],
    "Accuracy": [
        accuracy,
        accuracy_dt,
        accuracy_rf,
        accuracy_et,
        accuracy_xgb
    ],
    "Precision": [
        precision,
        precision_dt,
        precision_rf,
        precision_et,
        precision_xgb
    ],
    "Recall": [
        recall,
        recall_dt,
        recall_rf,
        recall_et,
        recall_xgb
    ],
    "F1 Score": [
        f1,
        f1_dt,
        f1_rf,
        f1_et,
        f1_xgb
    ],
    "ROC AUC": [
        roc_auc,
        roc_auc_dt,
        roc_auc_rf,
        roc_auc_et,
        roc_auc_xgb
    ]
})

classification_results

,Model,Accuracy,Precision,Recall,F1 Score,ROC AUC
0,Logistic Regression,0.93460,0.936966,0.937613,0.937289,0.987433
1,Decision Tree,0.99998,0.999962,1.000000,0.999981,0.999979
2,Random Forest,0.99868,0.997550,0.999923,0.998735,0.999984
3,Extra Trees,0.92466,0.928571,0.926754,0.927662,0.980200
4,XGBoost,0.99978,1.000000,0.999578,0.999789,0.999998


In [ ]:
# Save Classification Results

os.makedirs("../models", exist_ok=True)

classification_results.to_csv(
    "../models/classification_results.csv",
    index=False
)

print("Classification results saved successfully.")

Classification results saved successfully.


In [ ]:
# Save Classification Models

joblib.dump(
    logistic_model,
    "../models/logistic_regression.pkl"
)

joblib.dump(
    decision_tree_model,
    "../models/decision_tree.pkl"
)

joblib.dump(
    random_forest_model,
    "../models/random_forest.pkl"
)

joblib.dump(
    extra_trees_model,
    "../models/extra_trees.pkl"
)

joblib.dump(
    xgb_model,
    "../models/xgboost_classifier.pkl"
)

print("All classification models saved successfully.")

All classification models saved successfully.
